/* //** Hata Yönetimi İçin try-catch Kullanımı */

let products;

try {
    products.forEach(item => console.log(item));
} catch (error){
    console.log("error", error);
}
console.log("hata yönetimi düzgün çalışıyor")

let info="kodluyoruz"
console.log(info)

